#BreakoutDeterministic-v0
env: Breakout-v0
gamehacks: False
planner:
    batch_size: 128
    train_factor: 8
    max_mem: 1000
converter:
    height: 84
    width: 64
    history: 3
model:
    #loss: 0.0020 - action_out_loss: 0.0137 - value_out_loss: 0.0022 - entropy_loss: -1.3862
    type: conv
    act_coef: 1
    vf_coef: 0.5
    ent_coef: 0
    ppo_clip: 0.1
    lr: 0.0003
    epochs: 2
    expected_value: 0.3
agent:
    discount_gamma: 0.96
    end_reward: -1
    discount_mix: 0.9
    max_reward: 1
