#BreakoutDeterministic-v0
env: Breakout-v0
gamehacks: false
planner:
    batch_size: 128
    min_batches: 6
converter:
    height: 84
    width: 64
    history: 3
model:
    #loss: 0.0020 - action_out_loss: 0.0137 - value_out_loss: 0.0022 - entropy_loss: -1.3862
    type: conv
    act_coef: 0.3
    vf_coef: 5
    ent_coef: 0.01
    ppo_clip: 0.2
    lr: 0.0003
    epochs: 4
    expected_value: 0.4
agent:
    discount_gamma: 0.99
    end_reward: 0
    #discount_mix: 0.9
    max_reward: 1
