env: CartPole-v1
planner:
    batch_size: 64
    train_factor: 4
    max_mem: 2000
    min_mem: 400
converter:
    type: flat
model:
    type: dense
    act_coef: 0.1
    vf_coef: 10
    ent_coef: 0.000001
    ppo_clip: 0.1
    lr: 0.0001
    expected_value: -50
agent:
    discount_gamma: 0.95
    end_reward: -100
    discount_mix: 1
    max_reward: 1
