env: CartPole-v1
planner:
    batch_size: 128
    min_batches: 3
    #max_batches: 5
converter:
    type: flat
model:
    type: dense
    act_coef: 1
    vf_coef: 1
    ent_coef: 0.0001
    ppo_clip: 0.5
    lr: 0.001
    end_lr: 0
    epochs: 6
    expected_value: 6
    train_steps: 130
    end_ppo_clip: 0
agent:
    discount_gamma: 0.9
    end_reward: 0
    max_reward: 1
