env: LunarLander-v2
planner:
    batch_size: 1024
    min_batches: 2
converter:
    type: flat
model:
    type: dense
    act_coef: 1
    vf_coef: 0.5
    ent_coef: 0.001
    ppo_clip: 0.1
    lr: 0.00025
    epochs: 10
    expected_value: -20
    normalize_advantage: True
    #train_steps: 20
    #end_ppo_clip: 0
agent:
    discount_gamma: 0.99
    gae_lambda: 0.9
    end_reward: 0
    max_reward: 1000
