env: SpaceInvaders-v0
gamehacks: false
planner:
    batch_size: 32
    min_batches: 8
converter:
    height: 110
    width: 84
    history: 4
    colored: True
model:
    type: conv
    act_coef: 1
    vf_coef: 1
    ent_coef: 0.01
    ppo_clip: 0.1
    lr: 0.0003
    epochs: 3
    expected_value: 0.3
    normalize_advantage: True
    #normalize_advantage: False
    train_steps: 100000
    end_ppo_clip: 0
    end_lr: 0
rewardShaper:
    discount_gamma: 0.99
    gae_lambda: 0.8
executor:
    samples: 32
    workers: 8
agent:
    end_reward: 0
    max_reward: 1
